config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    passwords: 'passwords',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :users, only: [ :show ] do
    collection do
      get :navigation
      get :achievements
      get :edit_password
      patch :update_password
    end
  end

  get 'admin/dashboard'

  namespace :admin do
    get 'unconfirmed'
    get 'imageless'
    resources :users, only: [:index, :show, :update]
    match 'settings', to: 'settings#edit', via: :get
    match 'settings', to: 'settings#update', via: [:put, :patch]
  end

  resources :topics, only: [:show]

  resources :edits, only: [:edit, :update, :destroy] do
    member do
      patch :apply
      patch :discard
    end
  end

  resources :reports, only: [:new, :create]
  scope :admin do
    resources :reports, except: [:new, :create], as: 'admin_reports'
  end

  resources :votes, only: [:create, :show] do
    collection do
      match 'show/:id', to: 'votes#for_show', via: :get, as: :show
      match 'person/:id', to: 'votes#for_person', via: :get, as: :person
      match 'show/:id/mine', to: 'votes#mine_for_show', via: :get, as: :my_show
      match 'person/:id/mine', to: 'votes#mine_for_person', via: :get, as: :my_person
    end
  end

  resources :people do
    resources :books do
      member do
        post :rate
        get :rating
      end
    end
    member do
      post :favorite
      get :votes, to: 'votes#for_person'
      get 'votes/mine', to: 'votes#mine_for_person'
      get :shows
      get :episodes
      get :about
      post :rate
      get :rating
      get :edits
      get :merge, to: 'people#merge_form'
      post :merge
    end
  end

  resources :shows do
    resources :people do
      collection do
        get 'previous', to: 'people#previously_on_show'
        get 'other', to: 'people#new_to_show'
      end
      member do
        get :show, to: 'people#for_show'
      end
    end
    resources :sources do
      member do
        get :fetch
        post :generate
      end
    end
    resources :episodes do
      get :appearances, to: 'episodes#appearances'
      post :appearances, to: 'episodes#appear'
      delete :appearances, to: 'episodes#disappear'
      member do
        post :rate
        get :rating
        get :edits
        get :merge, to: 'episodes#merge_form'
        post :merge
      end
    end
    member do
      match 'votes', to: 'votes#for_show', via: :get
      match 'votes/mine', to: 'votes#mine_for_show', via: :get
      post :rate
      get :rating
      get :edits
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      patch :read
    end
  end

  get 'search', to: 'application#search'

  get '/welcome', to: 'pages#welcome'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'
  get '/sitemap', to: 'pages#sitemap'

  match '/404', to: 'pages#not_found', via: :all
  match '/500', to: 'pages#internal_server_error', via: :all

  root 'pages#welcome'
end

app/models/edit.rb
# frozen_string_literal: true

class Edit < ApplicationRecord
  belongs_to :editable, polymorphic: true
  belongs_to :created_by, class_name: 'User'
  belongs_to :discarded_by, class_name: 'User', optional: true
  belongs_to :applied_by, class_name: 'User', optional: true
  belongs_to :previous, class_name: 'Edit', optional: true
  has_one :next, class_name: 'Edit', foreign_key: :previous_id

  scope :applied, -> { where(applied: true) }
  scope :discarded, -> { where(discarded: true) }
  scope :pending, -> { where(discarded: false, applied: false) }

  validates :value, length: { minimum: 2 }
  validates :name, presence: true,
                   uniqueness: { scope: %i[editable_type editable_id created_by_id] }

  def pending?
    !applied? && !discarded?
  end

  def discard!(user)
    update(discarded: true, discarded_by: user, discarded_at: DateTime.now)
  end

  def apply!(user)
    editable.ensure_edit_for name, user
    self.previous = editable.last_applied_edit
    self.applied_by = user
    self.applied_at = DateTime.now
    self.applied = true
    return false unless save

    editable.update_attribute(name, value)
    editable.pending_edits.each do |edit|
      edit.discard!(user) if edit.name == name && edit.value == value
    end

    true
  end
end

app/controllers/edits_controller.rb
# frozen_string_literal: true

class EditsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resource

  # GET /edits/1/edit
  def edit
    authorize @edit, :update?
  end

  # PATCH/PUT /edits/1
  def update
    authorize @edit
    respond_to do |format|
      if @edit.update(edit_params)
        format.html { redirect_to edit_edit_path(@edit), notice: t('edit.notice.update') }
        format.js { render js: "window.location='#{edit_edit_path(@edit)}'" }
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # PATCH /edits/1/apply
  def apply
    authorize @edit
    respond_to do |format|
      if @edit.apply!(current_user)
        format.html { redirect_to redirect_path, notice: t('edit.notice.apply') }
      else
        format.html { redirect_to redirect_path, alert: @edit.errors.full_messages.join }
      end
    end
  end

  # PATCH /edits/1/discard
  def discard
    authorize @edit
    respond_to do |format|
      if @edit.discard!(current_user)
        format.html { redirect_to redirect_path, notice: t('edit.notice.discard') }
      else
        format.html { redirect_to redirect_path, alert: @edit.errors.full_messages.join }
      end
    end
  end

  # DELETE /edit/1
  def destroy
    authorize @edit
    @edit.destroy
    respond_to do |format|
      format.html { redirect_to redirect_path, notice: t('edit.notice.destroy') }
    end
  end

  private

  def set_resource
    @resource = @edit = Edit.find(params[:id])
  end

  def edit_params
    params.require(:edit).permit(:value)
  end

  def redirect_path
    request.referer.present? ? request.referer : url_for(@edit.editable)
  end
end

app/views/edits/edit.html.haml
:ruby
  title t('edit.edit.title', resource: @edit.editable, name: @edit.name)

  resource_singular = @edit.editable.class.to_s.parameterize

  @breadcrumbs = [
    { text: @edit.editable, link: url_for(@edit.editable) },
    { text: t('attributes.edits'), link: send("edits_#{resource_singular}_path", @edit.editable) },
    { text: @edit.name.capitalize }
  ]

.card
  .card-header= t('edit.edit.header', resource: @edit.editable, name: @edit.name)
  .card-body
    = form_with(model: @edit) do |form|
      .form-group
        = form.label :value, t("attributes.#{@edit.name}")
        = form.text_field :value, class: 'form-control', html: { 'aria-describedby': 'edit_value_info' }
        .invalid-feedback#edit_value_errors

      .actions.mt-4
        .d-flex
          .flex-grow-1
            = button_tag type: :submit, class: 'btn btn-primary mr-4' do
              %i.fas.fa-check
              %span.ml-1= t('form.save')

            = link_to t('form.cancel'), send("edits_#{resource_singular}_path", @edit.editable)

          .ml-2
            = link_to @edit, data: { method: :delete, confirm: t('confirm') }, class: 'btn btn-outline-danger' do
              %i.fa.fa-trash
              %span= t('button.destroy')

app/views/edits/index.html.haml
:ruby
  title t('edit.index.title', resource: @resource)

  @breadcrumbs = [
    { text: @resource, link: url_for(@resource) },
    { text: t('attributes.edits') }
  ]

.card
  .card-header.card-header-lg
    .d-flex.flex-row
      .flex-grow-1= t('edit.index.header', resource: @resource)

  - if @edits.empty?
    .card-body
      %p.card-text.text-center.text-muted.font-italic.my-5= t('edit.index.empty')

  - else
    .list-group-flush
      - @edits.each do |edit|
        .list-group-item.list-group-item-action
          .d-flex
            .flex-grow-1
              - if policy(@resource).update?
                = t('edit.suggested_by_html', user: link_to(edit.created_by, edit.created_by))
                = t('edit.name_html', name: edit.name, value: edit.value)
              - else
                = link_to t('edit.name_html', name: edit.name, value: edit.value), edit_edit_path(edit)
            .ml-2
              - if policy(@resource).update?
                = link_to apply_edit_path(edit), 'data-method': :patch, 'data-confirm': t('confirm'),
                    title: t('edit.hints.apply') do
                  %i.text-success.fa.fa-fw.fa-check

                = link_to discard_edit_path(edit), 'data-method': :patch, 'data-confirm': t('confirm'),
                    title: t('edit.hints.discard'), class: 'ml-2' do
                  %i.text-danger.fa.fa-fw.fa-times

              - else
                = link_to edit_path(edit), 'data-method': :delete, 'data-confirm': t('confirm'),
                    title: t('edit.hints.destroy') do
                  %i.text-danger.fa.fa-fw.fa-trash

app/views/edits/update.js.erb
$('.is-invalid').removeClass('is-invalid')

<% if @edit.errors.any? %>

  <%- @edit.errors.each do |attribute, error| %>
    $('#edit_<%= attribute %>').addClass('is-invalid')
    $('#edit_<%= attribute %>_errors').text('<%= attribute.to_s.titleize %> <%= error %>.')
  <% end %>

<% end %>