config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    passwords: 'passwords',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :users, only: [ :show ] do
    collection do
      get :navigation
      get :achievements
      get :edit_password
      patch :update_password
    end
  end

  get 'admin/dashboard'

  namespace :admin do
    get 'unconfirmed'
    get 'imageless'
    resources :users, only: [:index, :show, :update]
    match 'settings', to: 'settings#edit', via: :get
    match 'settings', to: 'settings#update', via: [:put, :patch]
  end

  resources :topics, only: [:show]

  resources :edits, only: [:edit, :update, :destroy] do
    member do
      patch :apply
      patch :discard
    end
  end

  resources :reports, only: [:new, :create]
  scope :admin do
    resources :reports, except: [:new, :create], as: 'admin_reports'
  end

  resources :votes, only: [:create, :show] do
    collection do
      match 'show/:id', to: 'votes#for_show', via: :get, as: :show
      match 'person/:id', to: 'votes#for_person', via: :get, as: :person
      match 'show/:id/mine', to: 'votes#mine_for_show', via: :get, as: :my_show
      match 'person/:id/mine', to: 'votes#mine_for_person', via: :get, as: :my_person
    end
  end

  resources :people do
    resources :books do
      member do
        post :rate
        get :rating
      end
    end
    member do
      post :favorite
      get :votes, to: 'votes#for_person'
      get 'votes/mine', to: 'votes#mine_for_person'
      get :shows
      get :episodes
      get :about
      post :rate
      get :rating
      get :edits
      get :merge, to: 'people#merge_form'
      post :merge
    end
  end

  resources :shows do
    resources :people do
      collection do
        get 'previous', to: 'people#previously_on_show'
        get 'other', to: 'people#new_to_show'
      end
      member do
        get :show, to: 'people#for_show'
      end
    end
    resources :sources do
      member do
        get :fetch
        post :generate
      end
    end
    resources :episodes do
      get :appearances, to: 'episodes#appearances'
      post :appearances, to: 'episodes#appear'
      delete :appearances, to: 'episodes#disappear'
      member do
        post :rate
        get :rating
        get :edits
        get :merge, to: 'episodes#merge_form'
        post :merge
      end
    end
    member do
      match 'votes', to: 'votes#for_show', via: :get
      match 'votes/mine', to: 'votes#mine_for_show', via: :get
      post :rate
      get :rating
      get :edits
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      patch :read
    end
  end

  get 'search', to: 'application#search'

  get '/welcome', to: 'pages#welcome'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'
  get '/sitemap', to: 'pages#sitemap'

  match '/404', to: 'pages#not_found', via: :all
  match '/500', to: 'pages#internal_server_error', via: :all

  root 'pages#welcome'
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  include Searchable
  include Confirmable
  include Blockable
  include Slugable
  include Topicable
  include Imageable
  include Rateable
  include Editable
  include ExternalLinkable
  include Duplicatable
  include Aliasable

  has_many :votes, dependent: :destroy
  has_many :favorites, as: :favoritable
  has_many :appearances, dependent: :destroy
  has_many :hostings, dependent: :destroy
  has_many :episodes, through: :appearances
  has_many :shows, -> { distinct }, through: :episodes
  has_many :hosted_shows, through: :hostings, source: :show
  has_many :pseudonyms, dependent: :destroy
  has_many :unfulfilled_votes, -> { unfulfilled }, class_name: 'Vote'
  has_many :fulfilled_votes, -> { fulfilled }, class_name: 'Vote'
  has_and_belongs_to_many :books

  validates :slug, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 2 },
                   format: { with: /\A[a-z0-9_-]+\z/,
                             message: 'can only contain lowercase letters, numbers, underscore and dash' }
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 2 }

  attr_accessor :vote_data

  def favorited_by?(user)
    favorites.where(user_id: user).any?
  end

  def to_s
    name
  end

  def vote_count
    attributes['vote_count'] || votes.size
  end

  def any_votes_for?(opts = {})
    if opts[:show] && opts[:user]
      any_votes_for_show_and_user?(opts[:show], opts[:user])
    elsif opts[:show]
      any_votes_for_show?(opts[:show])
    elsif opts[:user]
      any_votes_for_user?(opts[:user])
    else
      votes.size.positive?
    end
  end

  def any_votes_for_show_and_user?(show, user)
    if user.is_a? User
      votes.map { |v| v.show_id == show.id && v.user_id == user.id }.any?
    else
      votes.map { |v| v.show_id == show.id && v.ip_address == user }.any?
    end
  end

  def any_votes_for_user?(user)
    if user.is_a? User
      votes.map { |v| v.user_id == user.id }.any?
    else
      votes.map { |v| v.ip_address == user }.any?
    end
  end

  def any_votes_for_show?(show)
    votes.map { |v| v.show_id == show.id }.any?
  end

  def self.top(show = nil)
    if show
      left_joins(:votes)
        .group(:id)
        .where('votes.show_id IS NULL OR votes.show_id = ?', show.id)
        .select('people.*, COUNT(nullif(votes.fulfilled, true)) as vote_count')
        .order('vote_count DESC')
    else
      left_joins(:votes)
        .group(:id)
        .select('people.*, COUNT(nullif(votes.fulfilled, true)) as vote_count')
        .order('vote_count DESC')
    end
  end

  def self.order_by_votes(show = nil)
    count = if show
              "case when votes.show_id = #{show.id} AND NOT votes.fulfilled then 1 else null end"
            else
              'nullif(votes.fulfilled, true)'
            end
    left_joins(:votes).group(:id)
                      .uniq!(:group)
                      .select("people.*, COUNT(#{count}) as vote_count")
                      .order(Arel.sql("COUNT(#{count}) DESC"))
  end

  private

  def copy_associations_to(original)
    [votes, appearances, hostings].each do |collection|
      copy_association collection, :person, original
    end

    copy_association slugs, :slugable_id, original.id
    copy_association aliases, :aliasable_id, original.id
    copy_association favorites, :favoritable_id, original.id
    copy_association topic_topicables, :topicable_id, original.id
    copy_association ratings, :rateable_id, original.id
    copy_association edits, :editable_id, original.id

    books.each { |book| book.authors << orignal unless original.in?(book.authors) }

    original.image.attach image.blob unless original.image.attached?
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  include Pagy::Backend
  include ConfirmableController
  include BlockableController
  include TopicableController
  include ImageableController
  include RateableController
  include EditableController
  include AliasableController

  before_action :authenticate_user!, only: %i[new create edit update destroy favorite merge_form merge]
  before_action :set_resource, except: %i[index new create previously_on_show new_to_show]
  before_action :set_edits, only: %i[show shows episodes about]
  before_action :set_show

  # GET /people
  # GET /people.json
  def index
    @people = if @show
                guests_for_show
              elsif params[:q].present?
                Person.search(params[:q])
              else
                Person.top
              end
    @people = @people.unblocked(current_user).confirmed(current_user).limit(params[:limit] || 20)
  end

  # GET /shows/1/guests/previous.json
  def previously_on_show
    @people = @show.people
                   .select('people.*, MAX(episodes.aired_at)')
                   .order('MAX(episodes.aired_at) DESC')
                   .group(:id)
                   .unblocked(current_user)
                   .confirmed(current_user)
    @pagy, @records = pagy_arel(@people, items: page_limit)
    @pagy_metadata = pagy_metadata(@pagy)
    render :paginated
  end

  # GET /shows/1/guests/other.json
  def new_to_show
    @people = @show.new_people.order_by_votes.unblocked(current_user).confirmed(current_user)
    @pagy, @records = pagy_arel(@people, items: page_limit)
    @pagy_metadata = pagy_metadata(@pagy)
    render :paginated
  end

  # GET /shows/1/people/1
  def for_show
    @returning = @person.in?(@show.people)
    @voted = current_user && current_user.unfulfilled_votes.where(person: @person, show: @show).any?
    @episodes = @person.episodes.unblocked(current_user).confirmed(current_user).order(aired_at: :desc).limit(5)
    @people = @show.people.unblocked(current_user).confirmed(current_user).top.limit(5)
    @last_episode = @person.episodes.where(show: @show).order(aired_at: :desc).first if @returning
  end

  # GET /people/1
  # GET /people/1.json
  def show
    render layout: 'person'
  end

  # GET /person/1/shows or /person/1/shows.json
  def shows
    @shows = @person.shows.select('shows.*, MAX(episodes.aired_at)').unblocked(current_user).confirmed(current_user)
                    .order('MAX(episodes.aired_at) DESC').group(:id)
    @pagy, @records = pagy(@shows, items: page_limit)
    @pagy_metadata = pagy_metadata(@pagy)
    render layout: 'person'
  end

  # GET /person/1/episodes or /person/1/episodes.json
  def episodes
    @episodes = @person.episodes.joins(:show).joins(:people).group(:id).unblocked(current_user).confirmed(current_user)
                       .order(aired_at: :desc)
    @pagy, @records = pagy(@episodes, items: page_limit)
    @pagy_metadata = pagy_metadata(@pagy)
    render layout: 'person'
  end

  # GET /person/1/about
  def about
    render layout: 'person'
  end

  # GET /people/new
  def new
    @person = Person.new
    authorize @person, :create?
  end

  # GET /people/1/edit
  def edit
    authorize @person
    save_redirect_path
    @cancel_path = saved_redirect_path || person_path(@person)
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new
    authorize @person

    respond_to do |format|
      if create_person(@person)
        flash[:notice] = t('person.notice.create')
        format.html { redirect_to @person }
        format.json { render :show, status: :created, location: @person }
        format.js { render js: "window.location='#{url_for(@person)}'" }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    authorize @person, :edit?
    respond_to do |format|
      if update_person
        flash[:notice] = successful_update_notice
        format.html { redirect_to after_update_path }
        format.json { render :show, status: :ok, location: @person }
        format.js { render js: "window.location='#{after_update_path}'" }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    authorize @person
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: t('person.notice.destroy') }
      format.json { head :no_content }
    end
  end

  # POST /people/1/favorite
  # POST /people/1/favorite.json
  def favorite
    authorize @person
    if @person.favorited_by? current_user
      @person.favorites.where(user: current_user).destroy_all
      notice = t('person.notice.unfollow')
    else
      @person.favorites.create(user: current_user)
      notice = t('person.notice.follow')
    end
    respond_to do |format|
      format.html { redirect_to person_url(@person), notice: notice }
      format.json { render :show, status: :ok, location: @person }
    end
  end

  def merge_form
    authorize @person, :merge?
    render :merge
  end

  def merge
    authorize @person
    @original = Person.find_by(slug: params[:original_id])

    respond_to do |format|
      if !@original
        flash[:missing] = t('person.merge.empty')
        format.html { render :merge }
        format.js
      elsif @person.duplicate_of! @original
        flash[:notice] = t('person.notice.merge', person: @person, original: @original)
        format.html { redirect_to @original }
        format.js { render js: "window.location='#{url_for(@original)}'" }
      else
        format.html { render :merge }
        format.js
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_resource
    @resource = @person = Person.find_by!(slug: params[:id])
  rescue ActiveRecord::RecordNotFound
    resource = Slug.find_by!(name: params[:id], slugable_type: 'Person').hit!.slugable
    redirect_to id: resource.to_param, status: :moved_permanently
  end

  def set_show
    @show = Show.find_by!(slug: params[:show_id]) if params[:show_id]
  rescue ActiveRecord::RecordNotFound
    resource = Slug.find_by!(name: params[:show_id], slugable_type: 'Show').hit!.slugable
    redirect_to show_id: resource.to_param, status: :moved_permanently
  end

  def set_edits
    @edits = edits_for @person
  end

  # Get a list of guests for a specific show.
  #
  # Parameter `mode` can be set to either `new` or `old` to specify whether the list should contain guests that has
  # never been on the show, or who has.
  def guests_for_show
    return unless @show

    case (params[:mode] || '').to_sym
    when :mine
      if current_user
        current_user.people_voted_on.where(votes: { show: @show })
      else
        Person.joins(:votes).where(votes: { ip_address: request.remote_ip, show: @show })
      end
    when :new
      @show.new_people.top(@show)
    when :old
      @show.people.top(@show)
    else
      Person.top(@show)
    end
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(
      :name, :description, :slug, :confirmed, :blocked, :image, :twitter, :facebook, :website, :wikipedia,
      aliases: [], topics: []
    )
  end

  # Create person model.
  def create_person(person)
    parameters = person_params
    return false unless update_resource_confirmation person, parameters
    return false unless update_resource_blockade person, parameters
    return false unless attach_image person, parameters

    person.attributes = parameters.except(:aliases, :topics)
    person.created_by = current_user
    person.generate_slug unless parameters[:slug]

    return false unless person.save
    return false unless update_aliases person, parameters
    return false unless update_topics person, parameters

    true
  end

  # Update person model.
  def update_person
    parameters = person_params # save result from method so it can be modified through the update calls
    return false unless update_resource_confirmation @person, parameters
    return false unless update_resource_blockade @person, parameters
    return false unless update_aliases @person, parameters
    return false unless update_topics @person, parameters
    return false unless attach_image @person, parameters
    return false unless create_edits @person, parameters

    true
  end

  def after_update_path
    return saved_redirect_path if saved_redirect_path.present?

    if person_params.keys.length == 1 && person_params[:confirmed]
      admin_unconfirmed_path
    else
      url_for(@person)
    end
  end
end

app/helpers/person_helper.rb
# frozen_string_literal: true

module PersonHelper
  def person_image(person)
    if person.image.attached?
      url_for(person.image)
    else
      image_url('placeholder-person.jpg')
    end
  end
end

app/views/people/_form.html.haml
- unless policy(person).update?

  .font-italic.alert-info.alert.d-flex
    %div
      %span.fa.fa-info-circle
    .ml-3= t('edit.hints.suggestion')

= form_with(model: person) do |form|

  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control', html: { 'aria-describedby': 'person_name_info' }
    .invalid-feedback#person_name_errors

  - if person.persisted? && policy(person).update?
    .form-group
      = form.label :slug
      = form.text_field :slug, class: 'form-control', html: { 'aria-describedby': 'person_slug_info' }
      .invalid-feedback#person_slug_errors
      %small.form-text.text-muted#person_slug_info= t('hints.slug')

  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control', rows: 3
    .invalid-feedback#person_description_errors

  - if policy(person).update?
    .form-group
      = form.label :aliases
      %tag-input{ 'aria-describedby': 'person_aliases_info', class: 'form-control pl-2 h-auto',
                  ':value': person.aliases.map(&:name).to_json, name: 'person[aliases]', id: 'person_aliases' }
      .invalid-feedback#person_aliases_errors
      %small.form-text.text-muted#person_aliases_info= t('person.hints.aliases')

    .form-group
      = form.label :topics
      %tag-input{ class: 'form-control pl-2 h-auto',
                  ':value': person.topics.map(&:name).to_json, name: 'person[topics]', id: 'person_topics' }
      .invalid-feedback#person_topics_errors

    .form-group
      = form.label :image
      %image-form{ image: person_image(person), resource: :person }
      .invalid-feedback#person_image_errors

  .form-group
    = form.label :twitter
    .input-group.mb-3
      .input-group-prepend
        %span.input-group-text https://twitter.com/
      = form.text_field :twitter, class: 'form-control'
    .invalid-feedback#person_twitter_errors

  .form-group
    = form.label :facebook
    .input-group.mb-3
      .input-group-prepend
        %span.input-group-text https://facebook.com/
      = form.text_field :facebook, class: 'form-control'
    .invalid-feedback#person_facebook_errors

  .form-group
    = form.label :wikipedia
    .input-group.mb-3
      .input-group-prepend
        %span.input-group-text https://en.wikipedia.com/wiki/
      = form.text_field :wikipedia, class: 'form-control'
    .invalid-feedback#person_wikipedia_errors

  .form-group
    = form.label :website
    = form.text_field :website, class: 'form-control'
    .invalid-feedback#person_website_errors

  - if person.persisted? && policy(person).confirm?
    .form-group
      .custom-control.custom-checkbox
        = form.check_box :confirmed?, class: 'custom-control-input'
        = form.label :confirmed, class: 'custom-control-label'

  - if person.persisted? && policy(person).block?
    .form-group
      .custom-control.custom-checkbox
        = form.check_box :blocked?, class: 'custom-control-input'
        = form.label :blocked, class: 'custom-control-label'

  .actions.mt-4
    = button_tag type: :submit, class: 'btn btn-primary mr-4' do
      %i.fas.fa-check
      %span.ml-1= t('form.save')

    = link_to_cancel person

app/views/people/_index.html.haml
- empty_message ||= t('person.index.empty')
- if people.empty?
  .card-body
    %p.card-text.text-center.text-muted.font-italic.my-5= empty_message
- else
  %ul.list-group.list-group-flush
    - people.each do |person|
      %li.list-group-item.d-flex
        // image
        .list-group-item-image
          = link_to person do
            = image_tag person_image(person), class: 'rounded shadow-sm border'

        // body
        .list-group-item-body

          // title
          %h5.list-group-item-title= link_to person.name, person

          // description
          .list-group-item-description
            - if person.description.present?
              = person.description
            - else
              .font-italic= t('description_empty')

          // meta data
          .row.list-group-item-meta
            .col-4.col-lg-3.list-group-item-meta-group
              .list-group-item-meta-label
                %i.fa.fa-fw.fa-tv
                %span= t('attributes.shows')
              .list-group-item-meta-value
                = person.shows.size

            .col-4.col-lg-3.list-group-item-meta-group
              .list-group-item-meta-label
                %i.fa.fa-fw.fa-tv
                %span= t('attributes.episodes')
              .list-group-item-meta-value
                = person.episodes.size

            .col-4.col-lg-3.list-group-item-meta-group
              .list-group-item-meta-label
                %i.fa.fa-fw.fa-thumbs-up
                %span= t('attributes.votes')
              .list-group-item-meta-value
                = person.vote_count

        // buttons
        - if user_signed_in?
          .list-group-item-buttons
            .dropdown
              %a{ type: :button, data: { toggle: :dropdown }, aria: { haspopup: true, expanded: false }, title: 'More' }
                %i.fa.fa-fw.fa-ellipsis-v
              .dropdown-menu.dropdown-menu-right
                - if policy(Report).create?
                  = link_to_report person, class: 'dropdown-item'

                - if policy(person).edit?
                  = link_to edit_person_path(person), class: 'dropdown-item' do
                    %i.fas.fa-fw.fa-pen
                    %span.ml-1= t('button.edit')

                - if policy(person).merge?
                  = link_to merge_person_path(person), class: 'dropdown-item' do
                    %i.fas.fa-fw.fa-compress-alt
                    %span.ml-1= t('button.merge')

                - if policy(person).destroy?
                  = link_to person, method: :delete, data: { confirm: t('confirm') },
                                    class: 'dropdown-item text-danger' do
                    %i.fas.fa-fw.fa-trash
                    %span.ml-1= t('button.destroy')

app/views/people/about.html.haml
:ruby
  title t('person.info.title', name: @person.name)
  meta_tag :description, t('person.info.description', name: @person.name)
  active_tab :about

.row
  .col-md-12.col-lg-4
    .card
      .card-header Information
      .card-body

        %dl.mt-2

          %dt= t('attributes.name')
          %dd= @person.name

          - if @person.topics.size.positive?
            %dt= t('attributes.topics')
            %dd= topics_for @person

          %dt= t('attributes.appearances')
          %dd= @person.appearances.size

          %dt= t('attributes.shows')
          %dd= @person.shows.size

          %dt= t('attributes.votes')
          %dd= @person.votes.size

          - if policy(@person).update? && @person.aliases.any?

            %dt= t('attributes.aliases')
            %dd= @person.aliases.pluck(:name).join(', ')

      - if user_signed_in?
        .card-footer
          = link_to_report @person, class: 'mr-xl-1 btn btn-sm btn-outline-danger'

    = render 'shared/share_card', share_text: @person.name

  .col-md-12.col-lg-8
    .card
      .card-header= t('attributes.description')
      .card-body.px-3.py-2
        - if @person.description.present?
          = @person.description
        - else
          .my-5.py-5.text-center.font-italic= t('description_empty')

app/views/people/create.js.erb
$('.is-invalid').removeClass('is-invalid')

<% if @person.errors.any? %>

  <%- @person.errors.each do |attribute, error| %>
    $('#person_<%= attribute %>').addClass('is-invalid')
    $('#person_<%= attribute %>_errors').text('<%= attribute.to_s.titleize %> <%= error %>.')
  <% end %>

<% end %>

app/views/people/edit.html.haml
:ruby
  title t('person.edit.title', name: @person.name)

  @breadcrumbs = [
    { text: t('activerecord.models.person.other'), link: people_path },
    { text: @person.name, link: person_path(@person) },
    { text: t('person.edit.breadcrumb'), link: edit_person_path(@person) }
  ]

.card
  .card-header= t('person.edit.title', name: @person.name)
  .card-body
    = render 'form', person: @person

app/views/people/episodes.html.haml
:ruby
  title t('person.episodes.title', name: @person.name)
  meta_tag :description, t('person.episodes.description', name: @person.name)
  active_tab :episodes

-# Episodes
%paginated-list{ url: episodes_person_url(@person, format: :json), header: t('person.show.episodes', name: @person),
                 prefix: 'episodes_', 'previous-label': 'Previous', 'next-label': 'Next' }

  %template{ 'v-slot:loading': '' }
    = render 'shared/skeleton/item'

  %template{ 'v-slot:content': 'slotProps' }
    %lists-episodes{ ':collection': 'slotProps.collection', 'empty-message': t('person.show.episodes_empty') }

app/views/people/for_show.html.haml
:ruby
  title t('person.for_show.title', person: @person, show: @show)
  if @returning
    header = t('person.for_show.return.header', person: @person, show: @show)
    meta_tag :description, t('person.for_show.return.header', person: @person, show: @show)
  else
    header = t('person.for_show.new.header', person: @person, show: @show)
    meta_tag :description, t('person.for_show.new.header', person: @person, show: @show)
  end


.profile.profile-duo.mb-4
  .d-flex.justify-content-center.align-items-end.profile-duo-images
    .p-2.bg-primary.rounded
      = link_to @person do
        = image_tag person_image(@person), class: 'rounded shadow-sm border'
    .bg-primary.text-secondary.profile-duo-plus +
    .p-2.bg-primary.rounded
      = link_to @show do
        = image_tag show_image(@show), class: 'rounded shadow-sm border'
  .bg-primary.text-secondary.rounded.p-3.pt-5.text-center.profile-duo-header.shadow
    %h2= header
    %p.lead
      - if @returning
        Would you like to see #{@person} come back onto #{@show}? Make your voice heard and vote right now!
      - else
        Would you like to see #{@person} come onto #{@show} as a guest? Make your voice heard and vote right now!

    .mt-3.mb-3
      - if @voted
        %button.mt-2.mt-lg-3.btn.btn-lg.btn-secondary{ disabled: true }
          %i.fa.fa-thumbs-up
          %span.ml-2 Already voted

      - else
        = link_to votes_path(vote: { person_id: @person.id, value: 1, show_id: @show.id }),
                                    method: :post, class: 'mt-2 mt-lg-3 btn btn-lg btn-secondary shadow' do
          %i.fa.fa-thumbs-up
          %span.ml-2 Vote now!

    .mt-2= render 'shared/share_list', share_text: header

- if @last_episode && @last_episode.youtube.present?
  .card
    .card-header Latest episode with #{@person} on YouTube
    .card-body.embed-youtube= render 'shared/youtube', episode: @last_episode
- elsif @last_episode && @last_episode.spotify.present?
  .card
    .card-header Latest episode with #{@person} on Spotify
    .card-body.embed-spotify= render 'shared/spotify', episode: @last_episode

.overflow-md-hidden
  .row
    .col-12.col-lg-8
      .card
        .card-header
          Episodes with #{@person}
        = render 'episodes/index', episodes: @episodes

    .col-12.col-lg-4
      .card
        .card-header
          Guests on #{@show}
        %ul.list-group.list-group-flush
          - if @people.empty?
            %li.list-group-item
              %p.text-center.font-italic.py-5 No guests found.
          - else
            - @people.each do |person|
              %li.list-group-item
                .d-flex
                  .mr-3
                    = image_tag person_image(person), class: 'rounded-circle border size-25'
                  .flex-grow-1
                    = link_to person, person

app/views/people/index.html.haml
:ruby
  title t('person.index.title')

.card
  .card-header.card-header-lg
    .d-flex.flex-row
      .flex-grow-1= t('person.index.title')
      - if policy(Person).create?
        = link_to new_person_path, class: 'btn btn-sm btn-secondary' do
          %i.fas.fa-plus
          %span.ml-lg-1.d-none.d-lg-inline= t('person.index.create_button')

  = render 'people/index', people: @people

app/views/people/merge.html.haml
:ruby
  title t('person.merge.title', name: @person.name)

.card
  .card-header.card-header-lg
    .d-flex.flex-row
      .flex-grow-1= t('person.merge.title', name: @person.name)

  .m-5
    = form_with do
      %merge{ url: person_url(@person, format: :json),
              searchUrl: people_url(format: :json),
              headerMerge: t('person.merge.header.merge'),
              headerWith: t('person.merge.header.with'),
              placeholder: t('person.merge.placeholder'),
              mergeButton: t('person.merge.submit') }
        %template{ 'v-slot:loading': '' }
          = render 'shared/skeleton/item'

      .text-center.mt-3
        = button_tag type: :submit, class: 'btn btn-lg btn-primary' do
          %i.fas.fa-compress-alt
          %span.ml-1= t('person.merge.submit')

app/views/people/merge.js.erb
$('.is-invalid').removeClass('is-invalid')
$('#error').hide()

<% if flash[:missing] %>
  $('#original_autocomplete').addClass('is-invalid')
  $('#original_autocomplete_errors').text('<%= flash[:missing] %>')
<% end %>

<% if flash[:error] %>
  $('#error').show()
  $('#error').text('<%= flash[:error] %>')
<% end %>

app/views/people/new.html.haml
:ruby
  title t('person.new.title')

  @breadcrumbs = [
    { text: t('activerecord.models.person.other'), link: people_path },
    { text: t('person.new.breadcrumb'), link: new_person_path }
  ]

.card
  .card-header= t('person.new.header')
  .card-body
    = render 'form', person: @person