config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    passwords: 'passwords',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :users, only: [ :show ] do
    collection do
      get :navigation
      get :achievements
      get :edit_password
      patch :update_password
    end
  end

  get 'admin/dashboard'

  namespace :admin do
    get 'unconfirmed'
    get 'imageless'
    resources :users, only: [:index, :show, :update]
    match 'settings', to: 'settings#edit', via: :get
    match 'settings', to: 'settings#update', via: [:put, :patch]
  end

  resources :topics, only: [:show]

  resources :edits, only: [:edit, :update, :destroy] do
    member do
      patch :apply
      patch :discard
    end
  end

  resources :reports, only: [:new, :create]
  scope :admin do
    resources :reports, except: [:new, :create], as: 'admin_reports'
  end

  resources :votes, only: [:create, :show] do
    collection do
      match 'show/:id', to: 'votes#for_show', via: :get, as: :show
      match 'person/:id', to: 'votes#for_person', via: :get, as: :person
      match 'show/:id/mine', to: 'votes#mine_for_show', via: :get, as: :my_show
      match 'person/:id/mine', to: 'votes#mine_for_person', via: :get, as: :my_person
    end
  end

  resources :people do
    resources :books do
      member do
        post :rate
        get :rating
      end
    end
    member do
      post :favorite
      get :votes, to: 'votes#for_person'
      get 'votes/mine', to: 'votes#mine_for_person'
      get :shows
      get :episodes
      get :about
      post :rate
      get :rating
      get :edits
      get :merge, to: 'people#merge_form'
      post :merge
    end
  end

  resources :shows do
    resources :people do
      collection do
        get 'previous', to: 'people#previously_on_show'
        get 'other', to: 'people#new_to_show'
      end
      member do
        get :show, to: 'people#for_show'
      end
    end
    resources :sources do
      member do
        get :fetch
        post :generate
      end
    end
    resources :episodes do
      get :appearances, to: 'episodes#appearances'
      post :appearances, to: 'episodes#appear'
      delete :appearances, to: 'episodes#disappear'
      member do
        post :rate
        get :rating
        get :edits
        get :merge, to: 'episodes#merge_form'
        post :merge
      end
    end
    member do
      match 'votes', to: 'votes#for_show', via: :get
      match 'votes/mine', to: 'votes#mine_for_show', via: :get
      post :rate
      get :rating
      get :edits
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      patch :read
    end
  end

  get 'search', to: 'application#search'

  get '/welcome', to: 'pages#welcome'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'
  get '/sitemap', to: 'pages#sitemap'

  match '/404', to: 'pages#not_found', via: :all
  match '/500', to: 'pages#internal_server_error', via: :all

  root 'pages#welcome'
end

app/views/admin/dashboard.html.haml
- title 'Admin dashboard'
.card-deck.mx-0
  .card
    .card-header
      Version
    .card-body.pt-1
      - @versions.each do |version|
        .row.py-2
          .col-6= version[:name]
          .col-6.text-monospace= version[:number]

  .card
    .card-header
      Statistics
    .card-body.pt-1
      - @statistics.each do |statistic|
        .row.py-2
          .col-6= statistic[:name].capitalize
          .col-6.text-monospace= statistic[:number]

  - if root?
    .card
      .card-header
        Recent users
      %ul.list-group.list-group-flush
        - @users.each do |user|
          %li.list-group-item
            = link_to user.username, admin_user_url(user)

.card-deck.mx-0.mt-4
  .card
    .card-header
      Recent shows
    %ul.list-group.list-group-flush
      - @shows.each do |show|
        %li.list-group-item.text-truncate
          = link_to show, show_url(show)

  .card
    .card-header
      Recent people
    %ul.list-group.list-group-flush
      - @people.each do |person|
        %li.list-group-item.text-truncate
          = link_to person, person_url(person)

  .card
    .card-header
      Recent episodes
    %ul.list-group.list-group-flush
      - @episodes.each do |episode|
        %li.list-group-item.text-truncate
          = link_to episode, episode_url(episode)

app/views/admin/imageless.html.haml
- title 'Resources without images'
.card
  .card-header
    People without image
    %span.badge.badge-secondary.ml-2
      = @people_count
  = render 'people/index', people: @people

.card
  .card-header
    Shows without image
    %span.badge.badge-secondary.ml-2
      = @shows_count
  = render 'shows/index', shows: @shows

.card
  .card-header
    Episodes without image
    %span.badge.badge-secondary.ml-2
      = @episodes_count
  = render 'episodes/index', episodes: @episodes

.card
  .card-header
    Books without image
    %span.badge.badge-secondary.ml-2
      = @books_count
  = render 'books/index', books: @books

app/views/admin/unconfirmed.html.haml
- title 'Unconfirmed resources'
.card
  .card-header
    Unconfirmed guests
    %span.badge.badge-secondary.ml-2
      = @people_count

  %ul.list-group.list-group-flush
    - @people.each do |person|
      %li.list-group-item
        .d-flex.w-100.row-gap-2.flex-wrap

          // image
          = image_tag person_image(person), class: 'align-self-start rounded shadow-sm border size-100 mr-2'

          // body
          .flex-grow-1.ml-2.text-truncate
            %h5.mb-1.text-truncate= link_to person.name, person
            .d-flex.flex-row
              .mr-5
                %small.font-weight-bold.text-upper.text-muted Created by
                %div= link_to person.created_by, person.created_by

          // buttons
          %div
            - if policy(person).confirm?
              = link_to person_url(person, { person: { confirmed: 1 } }),
                        class: 'btn btn-sm btn-outline-primary mr-2',
                        data: { method: :put } do
                %i.fas.fa-check
                %span.ml-1 Confirm

            - if policy(person).destroy?
              = link_to person, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do
                %i.fas.fa-trash
                %span.ml-1
                  Remove

.card
  .card-header
    Unconfirmed shows
    %span.badge.badge-secondary.ml-2
      = @shows_count

  %ul.list-group.list-group-flush
    - @shows.each do |show|
      %li.list-group-item
        .d-flex.w-100.row-gap-2.flex-wrap

          // image
          = image_tag show_image(show), class: 'align-self-start rounded shadow-sm border size-100 mr-2'

          // body
          .flex-grow-1.ml-2.text-truncate
            %h5.mb-1.text-truncate= link_to show.title, show
            .d-flex.flex-row
              .mr-5
                %small.font-weight-bold.text-upper.text-muted Created by
                %div= link_to show.created_by, show.created_by

          // buttons
          %div
            - if policy(show).confirm?
              = link_to show_url(show, { show: { confirmed: 1 } }),
                        class: 'btn btn-sm btn-outline-primary mr-2',
                        data: { method: :put } do
                %i.fas.fa-check
                %span.ml-1 Confirm

            - if policy(show).destroy?
              = link_to show, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do
                %i.fas.fa-trash
                %span.ml-1
                  Remove

.card
  .card-header
    Unconfirmed episodes
    %span.badge.badge-secondary.ml-2
      = @episodes_count

  %ul.list-group.list-group-flush
    - @episodes.each do |episode|
      %li.list-group-item
        .d-flex.w-100.row-gap-2.flex-wrap

          // image
          = image_tag episode_image(episode), class: 'align-self-start rounded shadow-sm border size-100 mr-2'

          // body
          .flex-grow-1.ml-2.text-truncate
            %h5.mb-1.text-truncate= link_to episode.title, episode
            .d-flex.flex-row
              .mr-5
                %small.font-weight-bold.text-upper.text-muted Created by
                %div= link_to episode.created_by, episode.created_by

          // buttons
          %div
            - if policy(episode).confirm?
              = link_to episode_url(episode, { episode: { confirmed: 1 } }),
                        class: 'btn btn-sm btn-outline-primary mr-2',
                        data: { method: :put } do
                %i.fas.fa-check
                %span.ml-1 Confirm

            - if policy(episode).destroy?
              = link_to episode, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do
                %i.fas.fa-trash
                %span.ml-1
                  Remove

.card
  .card-header
    Unconfirmed books
    %span.badge.badge-secondary.ml-2
      = @books_count

  %ul.list-group.list-group-flush
    - @books.each do |book|
      %li.list-group-item
        .d-flex.w-100.row-gap-2.flex-wrap

          // image
          = image_tag book_image(book), class: 'align-self-start rounded shadow-sm border size-100 mr-2'

          // body
          .flex-grow-1.ml-2.text-truncate
            %h5.mb-1.text-truncate= link_to book, person_book_url(book.authors.first, book)
            .d-flex.flex-row
              .mr-5
                %small.font-weight-bold.text-upper.text-muted Created by
                %div= link_to book.created_by, book.created_by

          // buttons
          %div
            - if policy(book).confirm?
              = link_to person_book_url(book.authors.first, book, { book: { confirmed: 1 } }),
                        class: 'btn btn-sm btn-outline-primary mr-2',
                        data: { method: :put } do
                %i.fas.fa-check
                %span.ml-1 Confirm

            - if policy(book).destroy?
              = link_to person_book_url(book.authors.first, book), method: :delete, data: { confirm: 'Are you sure?' },
                        class: 'btn btn-sm btn-danger' do
                %i.fas.fa-trash
                %span.ml-1
                  Remove