config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    passwords: 'passwords',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :users, only: [ :show ] do
    collection do
      get :navigation
      get :achievements
      get :edit_password
      patch :update_password
    end
  end

  get 'admin/dashboard'

  namespace :admin do
    get 'unconfirmed'
    get 'imageless'
    resources :users, only: [:index, :show, :update]
    match 'settings', to: 'settings#edit', via: :get
    match 'settings', to: 'settings#update', via: [:put, :patch]
  end

  resources :topics, only: [:show]

  resources :edits, only: [:edit, :update, :destroy] do
    member do
      patch :apply
      patch :discard
    end
  end

  resources :reports, only: [:new, :create]
  scope :admin do
    resources :reports, except: [:new, :create], as: 'admin_reports'
  end

  resources :votes, only: [:create, :show] do
    collection do
      match 'show/:id', to: 'votes#for_show', via: :get, as: :show
      match 'person/:id', to: 'votes#for_person', via: :get, as: :person
      match 'show/:id/mine', to: 'votes#mine_for_show', via: :get, as: :my_show
      match 'person/:id/mine', to: 'votes#mine_for_person', via: :get, as: :my_person
    end
  end

  resources :people do
    resources :books do
      member do
        post :rate
        get :rating
      end
    end
    member do
      post :favorite
      get :votes, to: 'votes#for_person'
      get 'votes/mine', to: 'votes#mine_for_person'
      get :shows
      get :episodes
      get :about
      post :rate
      get :rating
      get :edits
      get :merge, to: 'people#merge_form'
      post :merge
    end
  end

  resources :shows do
    resources :people do
      collection do
        get 'previous', to: 'people#previously_on_show'
        get 'other', to: 'people#new_to_show'
      end
      member do
        get :show, to: 'people#for_show'
      end
    end
    resources :sources do
      member do
        get :fetch
        post :generate
      end
    end
    resources :episodes do
      get :appearances, to: 'episodes#appearances'
      post :appearances, to: 'episodes#appear'
      delete :appearances, to: 'episodes#disappear'
      member do
        post :rate
        get :rating
        get :edits
        get :merge, to: 'episodes#merge_form'
        post :merge
      end
    end
    member do
      match 'votes', to: 'votes#for_show', via: :get
      match 'votes/mine', to: 'votes#mine_for_show', via: :get
      post :rate
      get :rating
      get :edits
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      patch :read
    end
  end

  get 'search', to: 'application#search'

  get '/welcome', to: 'pages#welcome'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'
  get '/sitemap', to: 'pages#sitemap'

  match '/404', to: 'pages#not_found', via: :all
  match '/500', to: 'pages#internal_server_error', via: :all

  root 'pages#welcome'
end

app/models/episode.rb
# frozen_string_literal: true

class Episode < ApplicationRecord
  include Searchable
  include Confirmable
  include Blockable
  include Slugable
  include Topicable
  include Imageable
  include Rateable
  include Editable
  include ExternalLinkable
  include Duplicatable
  include Aliasable

  belongs_to :show
  has_many :appearances, dependent: :destroy
  has_many :people, through: :appearances

  validates :slug, presence: true,
                   uniqueness: { case_sensitive: false, scope: :show },
                   length: { minimum: 2 },
                   format: { with: /\A[a-z0-9_-]+\z/,
                             message: 'can only contain lowercase letters, numbers, underscore and dash' }
  validates :title, presence: true,
                    uniqueness: { case_sensitive: false, scope: :show },
                    length: { minimum: 2 }

  search_field :title
  slugged_field :title
  aliased_field :title
  youtube_url_pattern 'https://youtube.com/watch?v=%s'
  spotify_url_pattern 'https://open.spotify.com/episode/%s'

  alias_attribute :display_name, :title

  def search_result_values
    {
      id: id,
      display: title,
      image: image
    }
  end

  def full_title
    "#{show.title} - #{title}"
  end

  def to_s
    title
  end

  def self.with_title(title)
    find_by_alias clean_name(title).downcase
  end

  def self.from_source(source_response)
    validate_source_response! source_response

    source_response['episodes'].each do |episode_json|
      validate_source_episode! episode_json

      episode = with_title(episode_json['title'])

      unless episode
        episode = new(
          title: episode_json['title'].squish,
          description: episode_json['description'],
          aired_at: episode_json['aired_at'].to_datetime,
          generated: true
        )
        episode.attach_image episode_json['image']
        episode.generate_slug
        episode.auto_confirm
        episode.save!
        episode.create_guests_from_list episode_json['guests']
      end

      episode.save_source_id source_response['source'], episode_json
    end
  end

  def save_source_id(source_json, episode_json)
    case source_json['kind']
    when 'youtube'
      update youtube: episode_json['source_id']
    when 'spotify'
      update spotify: episode_json['source_id']
    end
  end

  def self.validate_source_response!(response)
    raise 'Episodes are missing from payload.' unless response && response['episodes'].is_a?(Array)
  end

  def self.validate_source_episode!(episode)
    %w[
      title
      source_id
    ].each do |field|
      raise "Attribute #{field} is missing from episode in payload." unless episode[field]
    end
  end

  def create_guests_from_list(guest_list)
    return unless guest_list.present?

    guest_list.each do |guest_name|
      person = Person.find_by_alias guest_name
      person ||= Person.where(name: guest_name).first_or_create do |p|
        p.generated = true
        p.generate_slug
        p.auto_confirm
      end
      appearances.where(person: person).first_or_create
    end
  end

  private

  def copy_associations_to(original)
    copy_association appearances, :episode, original
    copy_association slugs, :slugable_id, original.id
    copy_association aliases, :aliasable_id, original.id
    copy_association topic_topicables, :topicable_id, original.id
    copy_association ratings, :rateable_id, original.id
    copy_association edits, :editable_id, original.id
    original.image.attach image.blob unless original.image.attached?
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController
  include Pagy::Backend
  include ConfirmableController
  include BlockableController
  include TopicableController
  include ImageableController
  include RateableController
  include EditableController
  include AliasableController

  before_action :authenticate_user!, except: %i[index show appearances rating]
  before_action :set_show
  before_action :set_person, only: :index
  before_action :set_resource, only: %i[show edit update destroy appearances appear disappear edits merge_form merge]

  # GET /show/X/episodes
  # GET /show/X/episodes.json
  def index
    @episodes = @show ? @show.episodes : @person.episodes
    @episodes = @episodes.search(params[:q]) if params[:q].present?
    @episodes = @episodes.unblocked(current_user).confirmed(current_user).order(aired_at: :desc)
    @pagy, @records = pagy(@episodes, items: page_limit)
    @pagy_metadata = pagy_metadata(@pagy)
  end

  # GET /show/X/episodes/1
  # GET /show/X/episodes/1.json
  def show
    @edits = edits_for @episode
    render layout: 'sidebar'
  end

  # GET /show/X/episodes/new
  def new
    @episode = Episode.new(show: @show)
    authorize @episode, :create?
  end

  # GET /show/X/episodes/1/edit
  def edit
    authorize @episode, :update?
    save_redirect_path
    @cancel_path = saved_redirect_path || episode_path(@episode)
  end

  # POST /show/X/episodes
  # POST /show/X/episodes.json
  def create
    @episode = Episode.new
    authorize @episode

    respond_to do |format|
      if create_episode(@episode)
        flash[:notice] = t('episode.notice.create')
        format.html { redirect_to [@show, @episode] }
        format.json { render :show, status: :created, location: [@show, @episode] }
        format.js { render js: "window.location='#{show_episode_url(@episode.show, @episode)}'" }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /show/X/episodes/1
  # PATCH/PUT /show/X/episodes/1.json
  def update
    authorize @episode, :edit?
    respond_to do |format|
      if update_episode
        flash[:notice] = successful_update_notice
        format.html { redirect_to after_update_path }
        format.json { render :show, status: :ok, location: [@show, @episode] }
        format.js { render js: "window.location='#{after_update_path}'" }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /show/X/episodes/1
  # DELETE /show/X/episodes/1.json
  def destroy
    authorize @episode
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to show_url(@show), notice: t('episode.notice.destroy') }
      format.json { head :no_content }
    end
  end

  # GET /show/X/episodes/1/appearances
  # GET /show/X/episodes/1/appearances.json
  def appearances; end

  # POST /show/X/episodes/1/appearances
  # POST /show/X/episodes/1/appearances.json
  def appear
    person = find_or_create_person(person_params[:name])
    appearance = @episode.appearances.new(person: person)
    respond_to do |format|
      if appearance.save
        notify_users(appearance)
        format.html { redirect_to [@show, @episode], notice: 'Guest was successfully added to episode.' }
        format.json { render :appearances, status: :ok, location: [@show, @episode] }
        format.js { render js: "window.location='#{show_episode_url(@episode.show, @episode)}'" }
      else
        @edits = edits_for @episode
        format.html { render :show }
        format.json { render json: appearance.errors.full_messages, status: :unprocessable_entity }
        format.js
      end
    end
  rescue ActiveRecord::RecordNotFound
    error = 'No such guest found.'
    respond_to do |format|
      format.html { render :show, alert: error, status: :not_found }
      format.json { render json: { error: error }, status: :not_found }
    end
  end

  # DELETE /show/X/episodes/1/appearances
  # DELETE /show/X/episodes/1/appearances.json
  def disappear
    person = find_or_create_person(person_params[:name])
    @episode.appearances.where(person: person).delete_all
    respond_to do |format|
      format.html { redirect_to [@show, @episode], notice: 'Guest was successfully removed from episode.' }
      format.json { render :show, status: :ok, location: [@show, @episode] }
      format.js { render js: "window.location='#{show_episode_url(@episode.show, @episode)}'" }
    end
  end

  # GET /show/X/episodes/1/merge
  def merge_form
    authorize @episode, :merge?
    render :merge
  end

  # POST /show/X/episodes/1/merge
  def merge
    authorize @episode
    @original = Episode.find_by(slug: params[:original_id])

    respond_to do |format|
      if !@original
        flash[:missing] = t('episode.merge.empty')
        format.html { render :merge }
        format.js
      elsif @episode.duplicate_of! @original
        flash[:notice] = t('episode.notice.merge', episode: @episode, original: @original)
        format.html { redirect_to @original }
        format.js { render js: "window.location='#{url_for(@original)}'" }
      else
        format.html { render :merge }
        format.js
      end
    end
  end

  private

  def set_resource
    @resource = @episode = @show.episodes.find_by!(slug: params[:id] || params[:episode_id])
  rescue ActiveRecord::RecordNotFound
    resource = Slug.find_by!(name: params[:id], slugable_type: 'Episode').hit!.slugable
    redirect_to id: resource.to_param, status: :moved_permanently
  end

  def set_show
    @show = Show.find_by!(slug: params[:show_id]) if params[:show_id].present?
  rescue ActiveRecord::RecordNotFound
    resource = Slug.find_by!(name: params[:show_id], slugable_type: 'Show').hit!.slugable
    redirect_to show_id: resource.to_param, status: :moved_permanently
  end

  def set_person
    @person = Person.find_by!(slug: params[:person_id]) if params[:person_id].present?
  rescue ActiveRecord::RecordNotFound
    resource = Slug.find_by!(name: params[:person_id], slugable_type: 'Person').hit!.slugable
    redirect_to person_id: resource.to_param, status: :moved_permanently
  end

  # Only allow a list of trusted parameters through.
  def episode_params
    params.require(:episode).permit(
      :slug, :title, :description, :aired_at, :youtube, :apple_podcast, :spotify, :website, :image, :confirmed,
      :blocked, aliases: [], topics: []
    )
  end

  def person_params
    params.require(:person).permit(:id, :name)
  end

  def notify_users(appearance)
    show_url = url_for([appearance.episode.show, appearance.episode])
    title = format('%<person>s appeared on a show', person: appearance.person.name)
    content = format('%<person>s appeared on the show %<show>s',
                     person: helpers.link_to(appearance.person.name, appearance.person),
                     show: helpers.link_to(appearance.episode.show.title, show_url))

    votes = appearance.episode.show.votes.where(person: appearance.person, fulfilled: false)
    votes.map(&:user).uniq.each do |user|
      user.notifications.create(
        title: title,
        content: content,
        image: appearance.person.image,
        read: false
      )
    end
    votes.update_all(fulfilled: true)
  end

  # Create episode model.
  def create_episode(episode)
    parameters = episode_params
    return false unless update_resource_confirmation episode, parameters
    return false unless update_resource_blockade episode, parameters
    return false unless attach_image episode, parameters

    episode.attributes = parameters.except(:aliases, :topics)
    episode.created_by = current_user
    episode.generate_slug unless parameters[:slug]
    episode.show = @show

    return false unless episode.save
    return false unless update_aliases episode, parameters
    return false unless update_topics episode, parameters

    true
  end

  # Update episode model.
  def update_episode
    parameters = episode_params # save result from method so it can be modified through the update calls
    return false unless update_resource_confirmation @episode, parameters
    return false unless update_resource_blockade @episode, parameters
    return false unless update_aliases @episode, parameters
    return false unless update_topics @episode, parameters
    return false unless attach_image @episode, parameters
    return false unless create_edits @episode, parameters

    true
  end

  def after_update_path
    return saved_redirect_path if saved_redirect_path.present?

    if episode_params.keys.length == 1 && episode_params[:confirmed]
      admin_unconfirmed_path
    else
      url_for(@episode)
    end
  end
end

app/helpers/episode_helper.rb
# frozen_string_literal: true

module EpisodeHelper
  def episode_meta_description(episode)
    "Check out who appeared on #{episode.title} on the podcast show #{episode.show.title}."
  end

  def episode_meta_keywords(episode)
    [
      'podcast',
      'show',
      'guests',
      episode.title
    ].join(',')
  end

  def episode_image(episode)
    if episode.image.attached?
      url_for(episode.image)
    elsif episode.show.image.attached?
      url_for(episode.show.image)
    else
      image_url('placeholder-show.svg')
    end
  end
end

app/views/episodes/_form.html.haml
- unless policy(episode).update?

  .font-italic.alert-info.alert.d-flex
    %div
      %span.fa.fa-info-circle
    .ml-3= t('hints.edit')

= form_with(model: episode, url: [episode.show, episode]) do |form|

  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'
    .invalid-feedback#episode_title_errors

  - if episode.persisted? && policy(episode).update?
    .form-group
      = form.label :slug
      = form.text_field :slug, class: 'form-control', html: { 'aria-describedby': 'episode_slug_info' }
      .invalid-feedback#episode_slug_errors
      %small.form-text.text-muted#episode_slug_info= t('hints.slug')

  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control', rows: 3
    .invalid-feedback#episode_description_errors

  .form-group
    = form.label :aired_at
    = form.date_field :aired_at, class: 'form-control'
    .invalid-feedback#episode_aired_at_errors

  - if policy(episode).update?
    .form-group
      = form.label :aliases
      %tag-input{ 'aria-describedby': 'episode_aliases_info', class: 'form-control pl-2 h-auto',
                  ':value': episode.aliases.map(&:name).to_json, name: 'episode[aliases]', id: 'episode_aliases' }
      .invalid-feedback#episode_aliases_errors
      %small.form-text.text-muted#episode_aliases_info= t('episode.hints.aliases')

    .form-group
      = form.label :topics
      %tag-input{ class: 'form-control pl-2 h-auto',
                  ':value': episode.topics.map(&:name).to_json, name: 'episode[topics]', id: 'episode_topics' }
      .invalid-feedback#episode_topics_errors

    .form-group
      = form.label :image
      %image-form{ image: episode_image(episode), resource: :episode }
      .invalid-feedback#episode_image_errors

    - if episode.persisted? && policy(episode).confirm?
      .form-group
        .custom-control.custom-checkbox
          = form.check_box :confirmed?, class: 'custom-control-input'
          = form.label :confirmed, class: 'custom-control-label'

    - if episode.persisted? && policy(episode).block?
      .form-group
        .custom-control.custom-checkbox
          = form.check_box :blocked?, class: 'custom-control-input'
          = form.label :blocked, class: 'custom-control-label'

  .form-group
    = form.label :youtube
    .input-group.mb-3
      .input-group-prepend
        %span.input-group-text https://youtube.com/watch?v=
      = form.text_field :youtube, class: 'form-control'
    .invalid-feedback#episode_youtube_errors

  .form-group
    = form.label :apple_podcast
    .input-group.mb-3
      .input-group-prepend
        %span.input-group-text https://podcasts.apple.com/
      = form.text_field :apple_podcast, class: 'form-control'
    .invalid-feedback#episode_apple_podcast_errors

  .form-group
    = form.label :spotify
    .input-group.mb-3
      .input-group-prepend
        %span.input-group-text https://open.spotify.com/episode/
      = form.text_field :spotify, class: 'form-control'
    .invalid-feedback#episode_spotify_errors

  .form-group
    = form.label :website
    = form.text_field :website, class: 'form-control'
    .invalid-feedback#episode_website_errors

  .actions.mt-4
    = button_tag type: :submit, class: 'btn btn-primary mr-4' do
      %i.fas.fa-check
      %span.ml-1= t('form.save')

    = link_to_cancel episode, show_url(episode.show)

app/views/episodes/_index.html.haml
- empty_message ||= t('episode.index.empty')
- if episodes.empty?
  .card-body
    %p.card-text.text-center.text-muted.font-italic.my-5= empty_message
- else
  %ul.list-group.list-group-flush
    - episodes.each do |episode|
      %li.list-group-item.d-flex
        // image
        .list-group-item-image
          = link_to episode do
            = image_tag episode_image(episode), class: 'rounded shadow-sm border'

        // body
        .list-group-item-body

          // title
          %h5.list-group-item-title= link_to episode.title, episode

          // description
          .list-group-item-description
            - if episode.description.present?
              = episode.description
            - else
              .font-italic= t('description_empty')

          // meta data
          .row.list-group-item-meta

            .col-12.col-md-4.col-lg-3.list-group-item-meta-group
              .list-group-item-meta-label
                %i.fa.fa-fw.fa-tv
                %span= t('attributes.show')
              .list-group-item-meta-value
                = link_to episode.show.title, episode.show

            .col-12.col-md-4.col-lg-3.list-group-item-meta-group
              .list-group-item-meta-label
                %i.far.fa-fw.fa-calendar
                %span= t('attributes.aired_at')
              .list-group-item-meta-value
                = display_date(episode.aired_at, :long)

            .col-12.col-md-4.col-lg-6.list-group-item-meta-group
              .list-group-item-meta-label
                %i.fa.fa-fw.fa-user-tie
                %span= t('attributes.guests')
              .list-group-item-meta-value
                = episode.people.map { |p| link_to(p.name, p) }.join(', ').html_safe

        // buttons
        - if user_signed_in?
          .list-group-item-buttons
            .dropdown
              %a{ type: :button, data: { toggle: :dropdown }, aria: { haspopup: true, expanded: false } }
                %i.fa.fa-fw.fa-ellipsis-v
              .dropdown-menu.dropdown-menu-right
                - if policy(Report).create?
                  = link_to_report episode, class: 'dropdown-item'

                - if policy(episode).edit?
                  = link_to edit_show_episode_path(episode.show, episode), class: 'dropdown-item' do
                    %i.fas.fa-fw.fa-pen
                    %span.ml-1= t('button.edit')

                - if policy(episode).merge?
                  = link_to merge_show_episode_path(episode.show, episode), class: 'dropdown-item' do
                    %i.fas.fa-fw.fa-compress-alt
                    %span.ml-1= t('button.merge')

                - if policy(episode).destroy?
                  = link_to episode, method: :delete, data: { confirm: t('confirm') },
                                    class: 'dropdown-item text-danger' do
                    %i.fas.fa-fw.fa-trash
                    %span.ml-1= t('button.destroy')

app/views/episodes/create.js.erb
$('.is-invalid').removeClass('is-invalid')

<% if @episode.errors.any? %>

  <%- @episode.errors.each do |attribute, error| %>
    $('#episode_<%= attribute %>').addClass('is-invalid')
    $('#episode_<%= attribute %>_errors').text('<%= attribute.to_s.titleize %> <%= error %>.')
  <% end %>

<% end %>

app/views/episodes/edit.html.haml
:ruby
  title "Edit #{@episode.title}"

  @breadcrumbs = [
    { text: 'Shows', link: shows_path },
    { text: @episode.show, link: show_path(@episode.show) },
    { text: 'Episodes' },
    { text: @episode, link: episode_path(@episode) },
    { text: 'Edit', link: edit_show_episode_path(@episode.show, @episode) }
  ]

.card
  .card-header Edit #{@episode.title}
  .card-body
    = render 'form', episode: @episode

app/views/episodes/merge.html.haml
:ruby
  title t('episode.merge.title', title: @episode.title)

.card
  .card-header.card-header-lg
    .d-flex.flex-row
      .flex-grow-1= t('episode.merge.title', title: @episode.title)

  .m-5
    = form_with do
      %merge{ url: show_episode_url(@episode.show, @episode, format: :json),
              searchUrl: show_episodes_url(@episode.show, format: :json),
              headerMerge: t('episode.merge.header.merge'),
              headerWith: t('episode.merge.header.with'),
              placeholder: t('episode.merge.placeholder'),
              mergeButton: t('episode.merge.submit') }
        %template{ 'v-slot:loading': '' }
          = render 'shared/skeleton/item'

      .text-center.mt-3
        = button_tag type: :submit, class: 'btn btn-lg btn-primary' do
          %i.fas.fa-compress-alt
          %span.ml-1= t('episode.merge.submit')

app/views/episodes/merge.js.erb
$('.is-invalid').removeClass('is-invalid')
$('#error').hide()

<% if flash[:missing] %>
  $('#original_autocomplete').addClass('is-invalid')
  $('#original_autocomplete_errors').text('<%= flash[:missing] %>')
<% end %>

<% if flash[:error] %>
  $('#error').show()
  $('#error').text('<%= flash[:error] %>')
<% end %>

app/views/episodes/new.html.haml
:ruby
  title 'Add episode'

  @breadcrumbs = [
    { text: 'Shows', link: shows_path },
    { text: @episode.show, link: show_path(@episode.show) },
    { text: 'Episodes' },
    { text: 'Add', link: new_show_episode_path(@episode.show) }
  ]

.card
  .card-header Add episode
  .card-body
    = render 'form', episode: @episode

app/views/episodes/show.html.haml
:ruby
  title @episode.title
  meta_tag :description, episode_meta_description(@episode)
  meta_tag :description, episode_meta_keywords(@episode)

  @breadcrumbs = [
    { text: 'Shows', link: shows_path },
    { text: @episode.show, link: show_path(@episode.show) },
    { text: 'Episodes' },
    { text: @episode, link: episode_path(@episode) }
  ]

- content_for :sidebar do

  .card
    .card-header
      .d-none.d-lg-inline Information
      .d-lg-none= @episode.title

    .card-body
      = image_tag episode_image(@episode), class: 'mb-4 rounded shadow-sm border size-200'

      %dl

        %dt= t('attributes.title')
        %dd= @episode.title

        %dt= t('attributes.show')
        %dd= link_to @episode.show.title, @episode.show

        - if @episode.aired_at
          %dt= t('attributes.aired_at')
          %dd= display_date @episode.aired_at, :long

        - if @episode.topics.size.positive?
          %dt= t('attributes.topics')
          %dd= topics_for @episode
        - elsif @episode.show.topics.size.positive?
          %dt= t('attributes.topics')
          %dd= topics_for @episode.show

        %dt= t('attributes.rating')
        %dd.pt-1
          %rating{ 'rate-url': rate_show_episode_path(@episode.show, @episode, format: :json),
                   'rating-url': rating_show_episode_path(@episode.show, @episode, format: :json) }

        - if policy(@episode).edit? && @edits.present?
          %dt= t('attributes.edits')
          %dd= link_to t('edit.link', count: @edits.size), edits_episode_path(@episode)

        - if @episode.description
          %dt= t('attributes.description')
          %dd
            %small= sanitize(@episode.description.gsub("\n", '<br/>'))

    .card-footer
      = link_to_report @episode, class: 'mr-xl-1 btn btn-sm btn-outline-danger'

      - if policy(@episode).edit?
        = link_to edit_episode_path(@episode), class: 'btn btn-sm btn-outline-primary mr-1 mr-xl-2' do
          %i.fas.fa-pen
          %span.ml-1= t 'button.edit'

      - if policy(@episode).destroy?
        = link_to @episode, method: :delete, data: { confirm: t('confirm') }, class: 'btn btn-sm btn-danger' do
          %i.fas.fa-trash
          %span.ml-1= t 'button.destroy'

  = render 'shared/share_card', share_text: @episode.full_title

  - if @episode.external_links?
    .card
      .card-header External links
      .card-body
        %dl

          - if @episode.youtube.present?
            %dt
              %i.fab.fa-youtube.fa-fw
              %span.ml-1 YouTube
            %dd.text-truncate
              = link_to @episode.youtube_url, target: '_blank' do
                %span.text-muted https://youtube.com/watch?v=
                %span>= @episode.youtube

          - if @episode.apple_podcast.present?
            %dt
              %i.fab.fa-apple.fa-fw
              %span.ml-1 Apple Podcast
            %dd.text-truncate
              = link_to @episode.apple_podcast_url, target: '_blank' do
                %span.text-muted podcast.apple.com/
                %span>= @episode.apple_podcast

          - if @episode.spotify.present?
            %dt
              %i.fab.fa-spotify.fa-fw
              %span.ml-1 Spotify
            %dd.text-truncate
              = link_to @episode.spotify_url, target: '_blank' do
                %span.text-muted open.spotify.com/episode/
                %span>= @episode.spotify

          - if @episode.website.present?
            %dt
              %i.fas.fa-globe.fa-fw
              %span.ml-1 Website
            %dd.text-truncate
              = link_to @episode.website.sub(%r{^https?://(www.)?}, ''), @episode.website, target: '_blank'

- content_for :main do
  - if @episode.spotify.present?
    .card
      .card-header Listen on Spotify
      .card-body.embed-spotify= render 'shared/spotify', episode: @episode

  - if @episode.youtube.present?
    .card
      .card-header Watch on YouTube
      .card-body.embed-youtube= render 'shared/youtube', episode: @episode

  .card
    .card-header Guests on this episode
    %appearance-list{ url: show_episode_appearances_url(@episode.show, @episode, format: :json),
                      'show-add': policy(@episode).update? }

app/views/episodes/update.js.erb
$('.is-invalid').removeClass('is-invalid')

<% if @episode.errors.any? %>

  <%- @episode.errors.each do |attribute, error| %>
    $('#episode_<%= attribute %>').addClass('is-invalid')
    $('#episode_<%= attribute %>_errors').text('<%= attribute.to_s.titleize %> <%= error %>.')
  <% end %>

<% end %>